# Google Analytics
# See: https://analytics.google.com
google_analytics:
  tracking_id: UA-85214466-1
  # By default, NexT will load an external gtag.js script on your site.
  # If you only need the pageview feature, set the following option to true to get a better performance.
  only_pageview: false
  # only needed if you are using `only_pageview` mode, https://developers.google.com/analytics/devguides/collection/protocol/ga4
  measure_protocol_api_secret:

disqus:
  enable: true
  shortname: entropytk
  count: true
